name: freshchat_sdk
description: Freshchat is a modern messaging software for sales and customer engagement teams. freshchat_sdk (BETA) will help you integrate chat support in your mobile apps.
repository: https://github.com/freshworks/freshchat-flutter-sdk

# Whenever this version is updated, it must also be updated in Freshchat::getSdkVersion()
version: 0.10.23
homepage: https://www.freshworks.com/

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.freshchat.consumer.sdk.flutter
        pluginClass: FreshchatSdkPlugin
      ios:
        pluginClass: FreshchatSdkPlugin

assets:
  - pubspec.yaml
